<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                <span class="sr-only">Navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="index.php">
                <img src="./images/logo-dyna-100x50.png" alt=""/> Dynagroup Technologies</a>
        </div>
        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav navbar-right">
                <li><a href="index.php"><i class="glyphicon glyphicon-home"></i> Accueil</a></li>
                <li class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                        <i class="glyphicon glyphicon-info-sign"></i> Entreprise
                        <span class="caret"></span></a>
                    <ul class="dropdown-menu">
                        <li><a href="a_propos.php">A propos</a></li>
                        <li><a href="filiales.php">Synergie - Entreprises conjointes</a></li>
                    </ul>
                </li>
                <li class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#"> <i class="fa fa-cogs"></i> Services
                        <span class="caret"></span></a>
                    <ul class="dropdown-menu">
                        <li><a href="ingenierie-nouveaux-systemes.php">Ingénierie pour nouveaux systèmes</a></li>
                        <li><a href="etudes-de-systeme-existants">Études de système existants</a></li>
                        <li><a href="elaboration-de-devis.php">Élaboration de devis</a></li>
                        <li><a href="releves-de-terrain.php">Relevés de terrain</a></li>
                        <li><a href="installation-et-modification-d-un-systeme.php">Installation et modification d'un
                                système</a></li>
                    </ul>
                </li>
                <li>
                    <a href="contact.php"><i class="fa fa-envelope"></i> Contact</a>
                </li>
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-list-ol"></i>
                        Produits <b class="caret"></b></a>
                    <ul class="dropdown-menu">
                        <li>
                            <a href="depoussiereurs.php">Dépoussièreur</a>
                        </li>
                        <li>
                            <a href="cyclone.php">Cyclone</a>
                        </li>
                        <li>
                            <a href="preparateur.php">Pré-séparateur</a>
                        </li>
                        <li>
                            <a href=convoiement-pneumatique.php">Convoiement pneumatique</a>
                        </li>
                        <li>
                            <a href="fluidisation.php">Fluidisation</a>
                        </li>
                        <li>
                            <a href="canon-brumisation.php">Canon brumisation</a>
                        </li>
                        <li>
                            <a href="capture-a-la-source.php">Capture à la source</a>
                        </li>
                        <li>
                            <a href="elements-de-securite.php">Éléments de sécurité</a>
                        </li>
                        <li>
                            <a href="elements-filtrants.php">Éléments filtrants</a>
                        </li>
                        <li class="dropdown-submenu">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Équipements connexes</a>
                            <ul class="dropdown-menu">
                                <li><a href="evacuation-d-air.php">Évacuation d'air</a></li>
                                <li><a href=">Decharge-de-produits.php">Décharge de produits</a></li>
                                <li><a href="pieces-de-rechange.php">Pièces de rechange</a></li>
                            </ul>
                        </li>

                    </ul>
                </li>
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        <i class="fa fa-magic"></i> Champs d'expertise <b class="caret"></b></a>
                    <ul class="dropdown-menu">
                        <li>
                            <a href="asphalte-et-bitume.php">Asphalte et bitume</a>
                        </li>
                        <li>
                            <a href="carrieres.php">Carrières</a>
                        </li>
                        <li>
                            <a href="industrie-alimentaire.php">Industrie alimentaire</a>
                        </li>
                        <li>
                            <a href="industrie-divers.php">Industrie divers</a>
                        </li>
                    </ul>
                </li>

            </ul>

        </div>
        <!-- /.navbar-collapse -->
    </div>
    <!-- /.container -->
</nav>