<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                <span class="sr-only">Navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="index.php">
                <img src="./images/logo-dyna-100x50.png" alt=""/> Dynagroup Technologies</a>
        </div>
        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav navbar-right">
                <li><a href="index.php"><i class="glyphicon glyphicon-home"></i> Accueil</a></li>
                <li class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                        <i class="glyphicon glyphicon-info-sign"></i> Entreprise
                        <span class="caret"></span></a>
                    <ul class="dropdown-menu">
                        <li><a href="a_propos.php">A propos</a></li>
                        <li><a href="#">Synergie - Entreprises conjointes</a></li>
                    </ul>
                </li>
                <li class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#"> <i class="fa fa-cogs"></i> Services
                        <span class="caret"></span></a>
                    <ul class="dropdown-menu">
                        <li><a href="#">Ingénierie pour nouveaux systèmes</a></li>
                        <li><a href="#">Études de système existants</a></li>
                        <li><a href="#">Élaboration de devis</a></li>
                        <li><a href="#">Relevés de terrain</a></li>
                        <li><a href="#">Installation et modification d'un système</a></li>
                    </ul>
                </li>
                <li>
                    <a href="contact.php"><i class="fa fa-envelope"></i> Contact</a>
                </li>
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-list-ol"></i>
                        Produits <b class="caret"></b></a>
                    <ul class="dropdown-menu">
                        <li>
                            <a href="depoussiereurs.php">Dépoussièreur</a>
                        </li>
                        <li>
                            <a href="#">Cyclone</a>
                        </li>
                        <li>
                            <a href="#">Pré-séparateur</a>
                        </li>
                        <li>
                            <a href="#">Convoiement pneumatique</a>
                        </li>
                        <li>
                            <a href="#">Fluidisation</a>
                        </li>
                        <li>
                            <a href="#">Canon bruimisation</a>
                        </li>
                        <li>
                            <a href="#">Capture à la source</a>
                        </li>
                        <li>
                            <a href="#">Éléments de sécurité</a>
                        </li>
                        <li>
                            <a href="#">Éléments filtrants</a>
                        </li>
                        <li class="dropdown-submenu">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Équipements connexes</a>
                            <ul class="dropdown-menu">
                                <li><a href="#">Évacuation d'air</a></li>
                                <li><a href="#">Décharge de produits</a></li>
                                <li><a href="#">Pièces de rechange</a></li>
                            </ul>
                        </li>

                    </ul>
                </li>
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        <i class="fa fa-magic"></i> Champs d'expertise <b class="caret"></b></a>
                    <ul class="dropdown-menu">
                        <li>
                            <a href="#">Asphalte et bitume</a>
                        </li>
                        <li>
                            <a href="#">Carrières</a>
                        </li>
                        <li>
                            <a href="#">Industrie alimentaire</a>
                        </li>
                        <li>
                            <a href="#">Industrie divers</a>
                        </li>
                    </ul>
                </li>

            </ul>

        </div>
        <!-- /.navbar-collapse -->
    </div>
    <!-- /.container -->
</nav>