<ul class="list-unstyled list-inline list-social-icons">
    <li>
        <a href="#"><i class="fa fa-facebook-square fa-4x"></i></a>
    </li>
    <li>
        <a href="#"><i class="fa fa-linkedin-square fa-4x"></i></a>
    </li>
    <li>
        <a href="#"><i class="fa fa-twitter-square fa-4x"></i></a>
    </li>
    <li>
        <a href="#"><i class="fa fa-google-plus-square fa-4x"></i></a>
    </li>
</ul>