<!-- Portfolio Modals -->
<div class="portfolio-modal modal fade" id="portfolioModal5" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-content">
        <div class="close-modal" data-dismiss="modal">
            <div class="lr">
                <div class="rl">
                </div>
            </div>

        </div>
        <div class="container">
            <div class="row">
                <button type="button" class="btn btn-default" data-dismiss="modal"><i class="fa fa-times-circle-o"></i>
                    Fermer
                </button>
                <h2>Projet 5</h2>
                <hr class="star-primary">
                <div class="modal-body col-md-8">
                    <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
                        <!-- Indicators -->
                        <ol class="carousel-indicators">
                            <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
                            <li data-target="#carousel-example-generic" data-slide-to="1"></li>
                            <li data-target="#carousel-example-generic" data-slide-to="2"></li>
                        </ol>

                        <!-- Wrapper for slides -->
                        <div class="carousel-inner">
                            <div class="item active">
                                <img class="img-responsive" src="http://lorempixel.com/750/500/transport" alt="">
                            </div>
                            <div class="item">
                                <img class="img-responsive" src="http://lorempixel.com/750/500/animals" alt="">
                            </div>
                            <div class="item">
                                <img class="img-responsive" src="http://lorempixel.com/750/500/technics" alt="">
                            </div>
                        </div>

                        <!-- Controls -->
                        <a class="left carousel-control" href="#carousel-example-generic" data-slide="prev">
                            <span class="glyphicon glyphicon-chevron-left"></span>
                        </a>
                        <a class="right carousel-control" href="#carousel-example-generic" data-slide="next">
                            <span class="glyphicon glyphicon-chevron-right"></span>
                        </a>
                    </div>
                </div>
                <div class="col-md-4">
                    <h3>Description du projet</h3>

                    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam viverra euismod odio, gravida
                        pellentesque urna varius vitae. Sed dui lorem, adipiscing in adipiscing et, interdum nec metus.
                        Mauris ultricies, justo eu convallis placerat, felis enim.</p>

                    <h3>Détails du projet</h3>
                    <ul>
                        <li>Lorem Ipsum</li>
                        <li>Dolor Sit Amet</li>
                        <li>Consectetur</li>
                        <li>Adipiscing Elit</li>
                    </ul>
                </div>
            </div>
            <!-- /row1-->
            <div class="row">
                <div class="text-center">
                    <button type="button" class="btn btn-default" data-dismiss="modal"><i
                            class="fa fa-times-circle-o"></i>
                        Fermer
                    </button>
                </div>
            </div>
        </div>
        <!-- /row2-->
    </div>
</div>